alias blog="code ~/blog"
alias lab="code ~/lab"
alias ll="ls -ahlF --color=auto"
alias miri="cargo +nightly miri"
alias prune="git reflog expire --expire=now --all && git gc --prune=now"

eval "$(starship init zsh)"
